### ISSUE TITLE
The executable python3.5 (from --python=python3.5) does not exist

### ISSUE THREAD

**Issue by tomsitter** [timofurrer/try#2]
Hey,

I'm trying to run this on Windows 10. After installing via pip I'm running into a couple separate issues

1) `try` is masked by Windows PowerShell's try syntax
2) Running as a python m (`python -m try requests`) results in the error:
`The executable python3.5 (from --python=python3.5) does not exist`

I'm using Python 3.5 installed to C:\Python35\python.exe

Any help would be great!

**Comment by timofurrer** [comment]
Thanks for reporting :beers: 

1. That's a pity. I'm not a windows user.. Could you alias it? I might think about supporting `try` and `trypackage` as a command? What do you think?
2. On my linux machine the following works: `python3 -m try requests`. Is the error you could raised by `try` or from someone else? Do you have python-virtualenv installed (no idea how the package is called on windows. But you should have a virtualenv command available)? In addition to that .. does powershell support a `source` command to source the virtualenv? If not I'll have to make some changes to support windows

**Comment by tomsitter** [comment]
I found that try.exe works to launch it (i.e. `try.exe requests`) which resolves issue 1. This command points to `C:\Python35\Scripts\try.exe`

As for the second error, running the command results in this printout

```
> try.exe requests
==> Use python python3.5
[*] Downloading packages: requests
[*] Failed to try package. See C:\Users\Tom\AppData\Local\Temp\try-3k4_q9ih.log for more details.
```
With the log file contents being the text:
`The executable python3.5 (from --python=python3.5) does not exist`

**Comment by timofurrer** [comment]
Okay, thanks. I'll have a look at it as soon as possible!

**Comment by tomsitter** [comment]
Thanks, I added a few more details to my second comment.

**Comment by tomsitter** [comment]
I think this is coming from the second half of the` build_virtualenv_cmd` command.
Running the first part works fine (and gives the output noted in the final log contents above)
```
> virtualenv env -p C:/Python35/python.exe
Running virtualenv with interpreter C:/Python35/python.exe
Using base prefix 'C:\\Python35'
New python executable in env\Scripts\python.exe
Installing setuptools, pip, wheel...done.
```

But the second part `&& . env/bin/activate` is no good on windows. The equivalent would be 

`return "virtualenv env -p {0} > {1}; ./env/Scripts/activate".format(python_version, logfile)`

But unfortunately in powershell there are permission problems with virtualenv (discussed [here](https://virtualenv.pypa.io/en/latest/userguide.html))

**Comment by timofurrer** [comment]
> If I have time I will try to fork this and add windows support for running in Git Shell.

Any luck on that one?

**Comment by timofurrer** [comment]
**push**

**Comment by saurabhmarpadge** [comment]
Maybe it's because of python version.
$python3 --version
Python 3.4.0
So
from --python=python3.4
It worked

**Comment by Megaverse** [comment]
i did **virtualenv -p3 virtual_env_name** and this worked!

**Comment by timofurrer** [comment]
@saurabhmarpadge @Megaverse thanks for the confirmation. 
I'm going to close this for now! 

If anyone encounters the same issue please open a new ticket. 

:tada:

**Comment by manthankool** [comment]
The path python3.5 (from --python=python3.5) does not exist , how to remove this error , i was working on my railway api and this occurs

**Comment by timofurrer** [comment]
What exactly did you ran? And what was the exact error? @manthankool

**Comment by manthankool** [comment]
i was running this code  on cmd  **virtualenv venv --python=python3.5**  
and the error was:
**The path python3.5 (from --python=python3.5) does not exist**

**Comment by timofurrer** [comment]
> i was running this code on cmd virtualenv venv --python=python3.5

So, that's not really an issue of `try` then - because you are using plain `virtualenv`..

Have you installed `python3.5`? Can you run `python3.5` as an interpreter?

**Comment by manthankool** [comment]
yaa i have installed python 3.5 and i can also run python 3.5 as an interpreter . What should i do now ? @timofurrer

**Comment by timofurrer** [comment]
Unfortunately, I cannot help you because I don't have any Windows and because you have a problem with `virtualenv` and not with `try` I suggest to seek help on StackOverflow and tag your question with `python3`, `windows` and `virtualenv`. 
The `virtualenv` project is also hosted on GitHub and so is their issue tracker but I'd suggest you to ask on SO first.
